# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mobilitat_finestra4.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets



class mobilitat_programa(object):
    def setupUi(self, mobilitat_programa):
        mobilitat_programa.setObjectName("mobilitat_programa")
        mobilitat_programa.resize(1256, 884)
        self.MobilitatAplicacio = QtWidgets.QWidget(mobilitat_programa)
        self.MobilitatAplicacio.setObjectName("MobilitatAplicacio")
        self.tabWidget = QtWidgets.QTabWidget(self.MobilitatAplicacio)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 781, 311))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_assignacio = QtWidgets.QWidget()
        self.tab_assignacio.setEnabled(True)
        self.tab_assignacio.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tab_assignacio.setObjectName("tab_assignacio")
        self.btn_assignacio_automatica = QtWidgets.QPushButton(self.tab_assignacio)
        self.btn_assignacio_automatica.setGeometry(QtCore.QRect(480, 220, 141, 21))
        self.btn_assignacio_automatica.setObjectName("btn_assignacio_automatica")
        self.lbl_categoria_2 = QtWidgets.QLabel(self.tab_assignacio)
        self.lbl_categoria_2.setGeometry(QtCore.QRect(20, 20, 131, 20))
        self.lbl_categoria_2.setObjectName("lbl_categoria_2")
        self.cbx_torn_assignacio = QtWidgets.QComboBox(self.tab_assignacio)
        self.cbx_torn_assignacio.setGeometry(QtCore.QRect(170, 151, 111, 20))
        self.cbx_torn_assignacio.setObjectName("cbx_torn_assignacio")
        self.cbx_torn_assignacio.addItem("")
        self.cbx_torn_assignacio.addItem("")
        self.cbx_torn_assignacio.addItem("")
        self.cbx_torn_assignacio.addItem("")
        self.cbx_torn_assignacio.addItem("")
        self.lbl_torn_assignacio = QtWidgets.QLabel(self.tab_assignacio)
        self.lbl_torn_assignacio.setGeometry(QtCore.QRect(81, 151, 28, 16))
        self.lbl_torn_assignacio.setObjectName("lbl_torn_assignacio")
        self.cbx_parc_assignacio = QtWidgets.QComboBox(self.tab_assignacio)
        self.cbx_parc_assignacio.setGeometry(QtCore.QRect(170, 120, 111, 20))
        self.cbx_parc_assignacio.setObjectName("cbx_parc_assignacio")
        self.cbx_parc_assignacio.addItem("")
        self.cbx_parc_assignacio.addItem("")
        self.cbx_parc_assignacio.addItem("")
        self.cbx_parc_assignacio.addItem("")
        self.cbx_parc_assignacio.addItem("")
        self.cbx_categoria_general = QtWidgets.QComboBox(self.tab_assignacio)
        self.cbx_categoria_general.setGeometry(QtCore.QRect(170, 20, 101, 20))
        self.cbx_categoria_general.setObjectName("cbx_categoria_general")
        self.cbx_categoria_general.addItem("")
        self.cbx_categoria_general.addItem("")
        self.cbx_categoria_general.addItem("")
        self.cbx_categoria_general.addItem("")
        self.lbl_parc_assignacio = QtWidgets.QLabel(self.tab_assignacio)
        self.lbl_parc_assignacio.setGeometry(QtCore.QRect(81, 121, 27, 16))
        self.lbl_parc_assignacio.setObjectName("lbl_parc_assignacio")
        self.lbl_assignacio_manual = QtWidgets.QLabel(self.tab_assignacio)
        self.lbl_assignacio_manual.setGeometry(QtCore.QRect(70, 70, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_assignacio_manual.setFont(font)
        self.lbl_assignacio_manual.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_assignacio_manual.setObjectName("lbl_assignacio_manual")
        self.lbl_assignaci_automatica = QtWidgets.QLabel(self.tab_assignacio)
        self.lbl_assignaci_automatica.setGeometry(QtCore.QRect(420, 70, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_assignaci_automatica.setFont(font)
        self.lbl_assignaci_automatica.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_assignaci_automatica.setObjectName("lbl_assignaci_automatica")
        self.btn_assignacio_manual = QtWidgets.QPushButton(self.tab_assignacio)
        self.btn_assignacio_manual.setGeometry(QtCore.QRect(60, 220, 111, 23))
        self.btn_assignacio_manual.setObjectName("btn_assignacio_manual")
        self.lbl_matricula_assignacio = QtWidgets.QLabel(self.tab_assignacio)
        self.lbl_matricula_assignacio.setGeometry(QtCore.QRect(81, 181, 58, 16))
        self.lbl_matricula_assignacio.setObjectName("lbl_matricula_assignacio")
        self.led_matricula_assignacio = QtWidgets.QLineEdit(self.tab_assignacio)
        self.led_matricula_assignacio.setGeometry(QtCore.QRect(170, 181, 111, 20))
        self.led_matricula_assignacio.setObjectName("led_matricula_assignacio")
        self.btn_eliminacio_manual = QtWidgets.QPushButton(self.tab_assignacio)
        self.btn_eliminacio_manual.setGeometry(QtCore.QRect(200, 220, 111, 23))
        self.btn_eliminacio_manual.setObjectName("btn_eliminacio_manual")
        self.label_4 = QtWidgets.QLabel(self.tab_assignacio)
        self.label_4.setGeometry(QtCore.QRect(420, 120, 101, 20))
        self.label_4.setObjectName("label_4")
        self.led_matricula_seguent = QtWidgets.QLineEdit(self.tab_assignacio)
        self.led_matricula_seguent.setGeometry(QtCore.QRect(550, 120, 113, 20))
        self.led_matricula_seguent.setObjectName("led_matricula_seguent")
        self.label_5 = QtWidgets.QLabel(self.tab_assignacio)
        self.label_5.setGeometry(QtCore.QRect(420, 150, 101, 20))
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_assignacio)
        self.lineEdit_2.setGeometry(QtCore.QRect(550, 150, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tabWidget.addTab(self.tab_assignacio, "")
        self.tab_afegir_vacants = QtWidgets.QWidget()
        self.tab_afegir_vacants.setObjectName("tab_afegir_vacants")
        self.layoutWidget = QtWidgets.QWidget(self.tab_afegir_vacants)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 140, 211, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_categoria = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_categoria.setObjectName("lbl_categoria")
        self.horizontalLayout_3.addWidget(self.lbl_categoria)
        self.cbx_bomber = QtWidgets.QComboBox(self.layoutWidget)
        self.cbx_bomber.setObjectName("cbx_bomber")
        self.cbx_bomber.addItem("")
        self.cbx_bomber.addItem("")
        self.cbx_bomber.addItem("")
        self.cbx_bomber.addItem("")
        self.horizontalLayout_3.addWidget(self.cbx_bomber)
        self.lbl_titol_add_vacants = QtWidgets.QLabel(self.tab_afegir_vacants)
        self.lbl_titol_add_vacants.setGeometry(QtCore.QRect(20, 40, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titol_add_vacants.setFont(font)
        self.lbl_titol_add_vacants.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titol_add_vacants.setObjectName("lbl_titol_add_vacants")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_afegir_vacants)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 170, 211, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_vacants = QtWidgets.QLabel(self.layoutWidget1)
        self.lbl_vacants.setObjectName("lbl_vacants")
        self.horizontalLayout_4.addWidget(self.lbl_vacants)
        self.led_vacants = QtWidgets.QLineEdit(self.layoutWidget1)
        self.led_vacants.setObjectName("led_vacants")
        self.horizontalLayout_4.addWidget(self.led_vacants)
        self.btn_add_vacant = QtWidgets.QPushButton(self.tab_afegir_vacants)
        self.btn_add_vacant.setGeometry(QtCore.QRect(120, 210, 131, 23))
        self.btn_add_vacant.setObjectName("btn_add_vacant")
        self.table_vacants = QtWidgets.QTableWidget(self.tab_afegir_vacants)
        self.table_vacants.setGeometry(QtCore.QRect(280, 80, 411, 131))
        self.table_vacants.setObjectName("table_vacants")
        self.table_vacants.setColumnCount(4)
        self.table_vacants.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_vacants.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vacants.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vacants.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vacants.setHorizontalHeaderItem(3, item)
        self.table_vacants.horizontalHeader().setStretchLastSection(True)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_afegir_vacants)
        self.layoutWidget2.setGeometry(QtCore.QRect(40, 80, 211, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_parc = QtWidgets.QLabel(self.layoutWidget2)
        self.lbl_parc.setObjectName("lbl_parc")
        self.horizontalLayout.addWidget(self.lbl_parc)
        self.cbx_parc = QtWidgets.QComboBox(self.layoutWidget2)
        self.cbx_parc.setObjectName("cbx_parc")
        self.cbx_parc.addItem("")
        self.cbx_parc.addItem("")
        self.cbx_parc.addItem("")
        self.cbx_parc.addItem("")
        self.cbx_parc.addItem("")
        self.horizontalLayout.addWidget(self.cbx_parc)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_afegir_vacants)
        self.layoutWidget3.setGeometry(QtCore.QRect(40, 110, 211, 22))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_torn = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_torn.setObjectName("lbl_torn")
        self.horizontalLayout_2.addWidget(self.lbl_torn)
        self.cbx_torn = QtWidgets.QComboBox(self.layoutWidget3)
        self.cbx_torn.setObjectName("cbx_torn")
        self.cbx_torn.addItem("")
        self.cbx_torn.addItem("")
        self.cbx_torn.addItem("")
        self.cbx_torn.addItem("")
        self.cbx_torn.addItem("")
        self.horizontalLayout_2.addWidget(self.cbx_torn)
        self.lbl_titol_add_vacants_2 = QtWidgets.QLabel(self.tab_afegir_vacants)
        self.lbl_titol_add_vacants_2.setGeometry(QtCore.QRect(330, 40, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_titol_add_vacants_2.setFont(font)
        self.lbl_titol_add_vacants_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_titol_add_vacants_2.setObjectName("lbl_titol_add_vacants_2")
        self.tabWidget.addTab(self.tab_afegir_vacants, "")
        self.lbl_estat_vacants = QtWidgets.QLabel(self.MobilitatAplicacio)
        self.lbl_estat_vacants.setGeometry(QtCore.QRect(920, 50, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_estat_vacants.setFont(font)
        self.lbl_estat_vacants.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_estat_vacants.setObjectName("lbl_estat_vacants")
        self.table_vacants_estat = QtWidgets.QTableWidget(self.MobilitatAplicacio)
        self.table_vacants_estat.setGeometry(QtCore.QRect(930, 110, 231, 141))
        self.table_vacants_estat.setObjectName("table_vacants_estat")
        self.table_vacants_estat.setColumnCount(5)
        self.table_vacants_estat.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        item.setFont(font)
        self.table_vacants_estat.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_vacants_estat.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_vacants_estat.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_vacants_estat.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_vacants_estat.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_vacants_estat.setItem(4, 4, item)
        self.table_vacants_estat.horizontalHeader().setDefaultSectionSize(40)
        self.table_vacants_estat.horizontalHeader().setMinimumSectionSize(10)
        self.table_vacants_estat.verticalHeader().setVisible(True)
        self.table_vacants_estat.verticalHeader().setDefaultSectionSize(20)
        self.table_vacants_estat.verticalHeader().setHighlightSections(True)
        self.table_vacants_estat.verticalHeader().setMinimumSectionSize(15)
        self.lbl_panell_informacio = QtWidgets.QLabel(self.MobilitatAplicacio)
        self.lbl_panell_informacio.setGeometry(QtCore.QRect(230, 320, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_panell_informacio.setFont(font)
        self.lbl_panell_informacio.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_panell_informacio.setObjectName("lbl_panell_informacio")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.MobilitatAplicacio)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 360, 791, 461))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(False)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_2.setAutoFillBackground(True)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_2.setDocumentMode(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_estat_peticions = QtWidgets.QWidget()
        self.tab_estat_peticions.setObjectName("tab_estat_peticions")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_estat_peticions)
        self.tableWidget.setGeometry(QtCore.QRect(50, 40, 701, 351))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(self.tab_estat_peticions)
        self.label.setGeometry(QtCore.QRect(330, 10, 141, 20))
        self.label.setObjectName("label")
        self.tabWidget_2.addTab(self.tab_estat_peticions, "")
        self.tab_peticions_pendets = QtWidgets.QWidget()
        self.tab_peticions_pendets.setObjectName("tab_peticions_pendets")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_peticions_pendets)
        self.tableWidget_2.setGeometry(QtCore.QRect(40, 60, 711, 341))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.label_3 = QtWidgets.QLabel(self.tab_peticions_pendets)
        self.label_3.setGeometry(QtCore.QRect(290, 20, 261, 20))
        self.label_3.setObjectName("label_3")
        self.tabWidget_2.addTab(self.tab_peticions_pendets, "")
        self.tab_moviments = QtWidgets.QWidget()
        self.tab_moviments.setObjectName("tab_moviments")
        self.table_movimientos = QtWidgets.QTableWidget(self.tab_moviments)
        self.table_movimientos.setGeometry(QtCore.QRect(100, 40, 561, 341))
        self.table_movimientos.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.table_movimientos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_movimientos.setDragDropOverwriteMode(False)
        self.table_movimientos.setAlternatingRowColors(True)
        self.table_movimientos.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_movimientos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_movimientos.setTextElideMode(QtCore.Qt.ElideRight)
        self.table_movimientos.setWordWrap(False)
        self.table_movimientos.setObjectName("table_movimientos")
        self.table_movimientos.setColumnCount(5)
        self.table_movimientos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(57, 115, 172))
        self.table_movimientos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(57, 115, 172))
        self.table_movimientos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(57, 115, 172))
        self.table_movimientos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(57, 115, 172))
        self.table_movimientos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(57, 115, 172))
        self.table_movimientos.setHorizontalHeaderItem(4, item)
        self.table_movimientos.horizontalHeader().setDefaultSectionSize(100)
        self.table_movimientos.horizontalHeader().setMinimumSectionSize(50)
        self.table_movimientos.horizontalHeader().setStretchLastSection(True)
        self.table_movimientos.verticalHeader().setVisible(False)
        self.table_movimientos.verticalHeader().setDefaultSectionSize(20)
        self.table_movimientos.verticalHeader().setMinimumSectionSize(15)
        self.label_2 = QtWidgets.QLabel(self.tab_moviments)
        self.label_2.setGeometry(QtCore.QRect(300, 10, 151, 20))
        self.label_2.setObjectName("label_2")
        self.btn_guarda_assig = QtWidgets.QPushButton(self.tab_moviments)
        self.btn_guarda_assig.setGeometry(QtCore.QRect(300, 400, 141, 21))
        self.btn_guarda_assig.setObjectName("btn_guarda_assig")
        self.tabWidget_2.addTab(self.tab_moviments, "")
        self.lbl_estat_parcs = QtWidgets.QLabel(self.MobilitatAplicacio)
        self.lbl_estat_parcs.setGeometry(QtCore.QRect(1000, 330, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_estat_parcs.setFont(font)
        self.lbl_estat_parcs.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_estat_parcs.setObjectName("lbl_estat_parcs")
        self.table_estat_parcs = QtWidgets.QTableWidget(self.MobilitatAplicacio)
        self.table_estat_parcs.setGeometry(QtCore.QRect(890, 410, 331, 351))
        self.table_estat_parcs.setObjectName("table_estat_parcs")
        self.table_estat_parcs.setColumnCount(6)
        self.table_estat_parcs.setRowCount(25)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_estat_parcs.setHorizontalHeaderItem(5, item)
        self.table_estat_parcs.horizontalHeader().setDefaultSectionSize(40)
        self.table_estat_parcs.horizontalHeader().setMinimumSectionSize(10)
        self.table_estat_parcs.horizontalHeader().setSortIndicatorShown(False)
        self.table_estat_parcs.horizontalHeader().setStretchLastSection(False)
        mobilitat_programa.setCentralWidget(self.MobilitatAplicacio)
        self.mbr_principal = QtWidgets.QMenuBar(mobilitat_programa)
        self.mbr_principal.setGeometry(QtCore.QRect(0, 0, 1256, 21))
        self.mbr_principal.setObjectName("mbr_principal")
        self.mni_archivo = QtWidgets.QMenu(self.mbr_principal)
        self.mni_archivo.setObjectName("mni_archivo")
        mobilitat_programa.setMenuBar(self.mbr_principal)
        self.statusbar = QtWidgets.QStatusBar(mobilitat_programa)
        self.statusbar.setObjectName("statusbar")
        mobilitat_programa.setStatusBar(self.statusbar)
        self.mni_peticions = QtWidgets.QAction(mobilitat_programa)
        self.mni_peticions.setObjectName("mni_peticions")
        self.mni_vacants = QtWidgets.QAction(mobilitat_programa)
        self.mni_vacants.setObjectName("mni_vacants")
        self.mni_sortir = QtWidgets.QAction(mobilitat_programa)
        self.mni_sortir.setObjectName("mni_sortir")
        self.mni_personal = QtWidgets.QAction(mobilitat_programa)
        self.mni_personal.setObjectName("mni_personal")
        self.mni_archivo.addAction(self.mni_peticions)
        self.mni_archivo.addAction(self.mni_vacants)
        self.mni_archivo.addAction(self.mni_personal)
        self.mni_archivo.addSeparator()
        self.mni_archivo.addAction(self.mni_sortir)
        self.mbr_principal.addAction(self.mni_archivo.menuAction())

        self.retranslateUi(mobilitat_programa)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mobilitat_programa)

    def retranslateUi(self, mobilitat_programa):
        _translate = QtCore.QCoreApplication.translate
        mobilitat_programa.setWindowTitle(_translate("mobilitat_programa", "Mobilitat"))
        self.btn_assignacio_automatica.setText(_translate("mobilitat_programa", "Processa següent petició"))
        self.lbl_categoria_2.setText(_translate("mobilitat_programa", "Selecciona una categoria:"))
        self.cbx_torn_assignacio.setItemText(0, _translate("mobilitat_programa", "A"))
        self.cbx_torn_assignacio.setItemText(1, _translate("mobilitat_programa", "B"))
        self.cbx_torn_assignacio.setItemText(2, _translate("mobilitat_programa", "C"))
        self.cbx_torn_assignacio.setItemText(3, _translate("mobilitat_programa", "D"))
        self.cbx_torn_assignacio.setItemText(4, _translate("mobilitat_programa", "E"))
        self.lbl_torn_assignacio.setText(_translate("mobilitat_programa", "TORN"))
        self.cbx_parc_assignacio.setCurrentText(_translate("mobilitat_programa", "EIXAMPLE"))
        self.cbx_parc_assignacio.setItemText(0, _translate("mobilitat_programa", "EIXAMPLE"))
        self.cbx_parc_assignacio.setItemText(1, _translate("mobilitat_programa", "LLEVANT"))
        self.cbx_parc_assignacio.setItemText(2, _translate("mobilitat_programa", "MONTJUIC"))
        self.cbx_parc_assignacio.setItemText(3, _translate("mobilitat_programa", "SANT ANDREU"))
        self.cbx_parc_assignacio.setItemText(4, _translate("mobilitat_programa", "VALL HEBRON"))
        self.cbx_categoria_general.setItemText(0, _translate("mobilitat_programa", "BOMBER"))
        self.cbx_categoria_general.setItemText(1, _translate("mobilitat_programa", "CAPORAL"))
        self.cbx_categoria_general.setItemText(2, _translate("mobilitat_programa", "SERGENT"))
        self.cbx_categoria_general.setItemText(3, _translate("mobilitat_programa", "SUBMARINISTA"))
        self.lbl_parc_assignacio.setText(_translate("mobilitat_programa", "PARC"))
        self.lbl_assignacio_manual.setText(_translate("mobilitat_programa", "ASSIGNACIÓ MANUAL"))
        self.lbl_assignaci_automatica.setText(_translate("mobilitat_programa", "ASSIGNACIÓ AUTOMÀTICA"))
        self.btn_assignacio_manual.setText(_translate("mobilitat_programa", "Assignar vacant"))
        self.lbl_matricula_assignacio.setText(_translate("mobilitat_programa", "MATRICULA"))
        self.btn_eliminacio_manual.setText(_translate("mobilitat_programa", "Eliminar vacant"))
        self.label_4.setText(_translate("mobilitat_programa", "Següent Matricula:"))
        self.label_5.setText(_translate("mobilitat_programa", "Següent Petició:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_assignacio), _translate("mobilitat_programa", "Assignar vacants"))
        self.lbl_categoria.setText(_translate("mobilitat_programa", "CATEGORIA"))
        self.cbx_bomber.setItemText(0, _translate("mobilitat_programa", "BOMBER"))
        self.cbx_bomber.setItemText(1, _translate("mobilitat_programa", "CAPORAL"))
        self.cbx_bomber.setItemText(2, _translate("mobilitat_programa", "SERGENT"))
        self.cbx_bomber.setItemText(3, _translate("mobilitat_programa", "SUBMARINISTA"))
        self.lbl_titol_add_vacants.setText(_translate("mobilitat_programa", "AFEGIR VACANT"))
        self.lbl_vacants.setText(_translate("mobilitat_programa", "VACANTS/EXCES"))
        self.led_vacants.setText(_translate("mobilitat_programa", "0"))
        self.btn_add_vacant.setText(_translate("mobilitat_programa", "Afegir vacant/exces"))
        item = self.table_vacants.horizontalHeaderItem(0)
        item.setText(_translate("mobilitat_programa", "CATEGORIA"))
        item = self.table_vacants.horizontalHeaderItem(1)
        item.setText(_translate("mobilitat_programa", "PARC"))
        item = self.table_vacants.horizontalHeaderItem(2)
        item.setText(_translate("mobilitat_programa", "TORN"))
        item = self.table_vacants.horizontalHeaderItem(3)
        item.setText(_translate("mobilitat_programa", "VALOR"))
        self.lbl_parc.setText(_translate("mobilitat_programa", "PARC"))
        self.cbx_parc.setCurrentText(_translate("mobilitat_programa", "EIXAMPLE"))
        self.cbx_parc.setItemText(0, _translate("mobilitat_programa", "EIXAMPLE"))
        self.cbx_parc.setItemText(1, _translate("mobilitat_programa", "LLEVANT"))
        self.cbx_parc.setItemText(2, _translate("mobilitat_programa", "MONTJUIC"))
        self.cbx_parc.setItemText(3, _translate("mobilitat_programa", "SANT ANDREU"))
        self.cbx_parc.setItemText(4, _translate("mobilitat_programa", "VALL HEBRON"))
        self.lbl_torn.setText(_translate("mobilitat_programa", "TORN"))
        self.cbx_torn.setItemText(0, _translate("mobilitat_programa", "A"))
        self.cbx_torn.setItemText(1, _translate("mobilitat_programa", "B"))
        self.cbx_torn.setItemText(2, _translate("mobilitat_programa", "C"))
        self.cbx_torn.setItemText(3, _translate("mobilitat_programa", "D"))
        self.cbx_torn.setItemText(4, _translate("mobilitat_programa", "E"))
        self.lbl_titol_add_vacants_2.setText(_translate("mobilitat_programa", "VACANTS AFEGIDES"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_afegir_vacants), _translate("mobilitat_programa", "Afegir vacants"))
        self.lbl_estat_vacants.setText(_translate("mobilitat_programa", "VACANTS/EXCESSOS"))
        item = self.table_vacants_estat.verticalHeaderItem(0)
        item.setText(_translate("mobilitat_programa", "EX"))
        item = self.table_vacants_estat.verticalHeaderItem(1)
        item.setText(_translate("mobilitat_programa", "LL"))
        item = self.table_vacants_estat.verticalHeaderItem(2)
        item.setText(_translate("mobilitat_programa", "MJ"))
        item = self.table_vacants_estat.verticalHeaderItem(3)
        item.setText(_translate("mobilitat_programa", "SA"))
        item = self.table_vacants_estat.verticalHeaderItem(4)
        item.setText(_translate("mobilitat_programa", "VH"))
        item = self.table_vacants_estat.horizontalHeaderItem(0)
        item.setText(_translate("mobilitat_programa", "A"))
        item = self.table_vacants_estat.horizontalHeaderItem(1)
        item.setText(_translate("mobilitat_programa", "B"))
        item = self.table_vacants_estat.horizontalHeaderItem(2)
        item.setText(_translate("mobilitat_programa", "C"))
        item = self.table_vacants_estat.horizontalHeaderItem(3)
        item.setText(_translate("mobilitat_programa", "D"))
        item = self.table_vacants_estat.horizontalHeaderItem(4)
        item.setText(_translate("mobilitat_programa", "E"))
        __sortingEnabled = self.table_vacants_estat.isSortingEnabled()
        self.table_vacants_estat.setSortingEnabled(False)
        self.table_vacants_estat.setSortingEnabled(__sortingEnabled)
        self.lbl_panell_informacio.setText(_translate("mobilitat_programa", "PANELL D\'INFORMACIÓ"))
        self.label.setText(_translate("mobilitat_programa", "ESTAT PETICIONS"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_estat_peticions), _translate("mobilitat_programa", "Estat Peticions"))
        self.label_3.setText(_translate("mobilitat_programa", "PETICIONS NO HA CANVIAT DE DESTI ORDENADES"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_peticions_pendets), _translate("mobilitat_programa", "Peticions Pendents"))
        self.table_movimientos.setSortingEnabled(True)
        item = self.table_movimientos.horizontalHeaderItem(0)
        item.setText(_translate("mobilitat_programa", "MATRICULA"))
        item = self.table_movimientos.horizontalHeaderItem(1)
        item.setText(_translate("mobilitat_programa", "ORIGEN"))
        item = self.table_movimientos.horizontalHeaderItem(2)
        item.setText(_translate("mobilitat_programa", "ESTAT_ORIGEN"))
        item = self.table_movimientos.horizontalHeaderItem(3)
        item.setText(_translate("mobilitat_programa", "DESTI"))
        item = self.table_movimientos.horizontalHeaderItem(4)
        item.setText(_translate("mobilitat_programa", "ESTAT_DESTI"))
        self.label_2.setText(_translate("mobilitat_programa", "MOVIMENTS REALITZADES"))
        self.btn_guarda_assig.setText(_translate("mobilitat_programa", "Guarda Assignacions"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_moviments), _translate("mobilitat_programa", "Moviments Realitzats"))
        self.lbl_estat_parcs.setText(_translate("mobilitat_programa", "ESTAT PARCS"))
        item = self.table_estat_parcs.verticalHeaderItem(0)
        item.setText(_translate("mobilitat_programa", "EX-A"))
        item = self.table_estat_parcs.verticalHeaderItem(1)
        item.setText(_translate("mobilitat_programa", "EX-B"))
        item = self.table_estat_parcs.verticalHeaderItem(2)
        item.setText(_translate("mobilitat_programa", "EX-D"))
        item = self.table_estat_parcs.verticalHeaderItem(3)
        item.setText(_translate("mobilitat_programa", "EX-D"))
        item = self.table_estat_parcs.verticalHeaderItem(4)
        item.setText(_translate("mobilitat_programa", "EX-E"))
        item = self.table_estat_parcs.verticalHeaderItem(5)
        item.setText(_translate("mobilitat_programa", "LL-A"))
        item = self.table_estat_parcs.verticalHeaderItem(6)
        item.setText(_translate("mobilitat_programa", "LL-B"))
        item = self.table_estat_parcs.verticalHeaderItem(7)
        item.setText(_translate("mobilitat_programa", "LL-C"))
        item = self.table_estat_parcs.verticalHeaderItem(8)
        item.setText(_translate("mobilitat_programa", "LL-D"))
        item = self.table_estat_parcs.verticalHeaderItem(9)
        item.setText(_translate("mobilitat_programa", "LL-E"))
        item = self.table_estat_parcs.verticalHeaderItem(10)
        item.setText(_translate("mobilitat_programa", "MJ-A"))
        item = self.table_estat_parcs.verticalHeaderItem(11)
        item.setText(_translate("mobilitat_programa", "MJ-B"))
        item = self.table_estat_parcs.verticalHeaderItem(12)
        item.setText(_translate("mobilitat_programa", "MJ-C"))
        item = self.table_estat_parcs.verticalHeaderItem(13)
        item.setText(_translate("mobilitat_programa", "MJ-D"))
        item = self.table_estat_parcs.verticalHeaderItem(14)
        item.setText(_translate("mobilitat_programa", "MJ-E"))
        item = self.table_estat_parcs.verticalHeaderItem(15)
        item.setText(_translate("mobilitat_programa", "SA-A"))
        item = self.table_estat_parcs.verticalHeaderItem(16)
        item.setText(_translate("mobilitat_programa", "SA-B"))
        item = self.table_estat_parcs.verticalHeaderItem(17)
        item.setText(_translate("mobilitat_programa", "SA-C"))
        item = self.table_estat_parcs.verticalHeaderItem(18)
        item.setText(_translate("mobilitat_programa", "SA-D"))
        item = self.table_estat_parcs.verticalHeaderItem(19)
        item.setText(_translate("mobilitat_programa", "SA-E"))
        item = self.table_estat_parcs.verticalHeaderItem(20)
        item.setText(_translate("mobilitat_programa", "VH-A"))
        item = self.table_estat_parcs.verticalHeaderItem(21)
        item.setText(_translate("mobilitat_programa", "VH-B"))
        item = self.table_estat_parcs.verticalHeaderItem(22)
        item.setText(_translate("mobilitat_programa", "VH-C"))
        item = self.table_estat_parcs.verticalHeaderItem(23)
        item.setText(_translate("mobilitat_programa", "VH-D"))
        item = self.table_estat_parcs.verticalHeaderItem(24)
        item.setText(_translate("mobilitat_programa", "VH-E"))
        item = self.table_estat_parcs.horizontalHeaderItem(0)
        item.setText(_translate("mobilitat_programa", "SGT"))
        item = self.table_estat_parcs.horizontalHeaderItem(1)
        item.setText(_translate("mobilitat_programa", "CAP"))
        item = self.table_estat_parcs.horizontalHeaderItem(2)
        item.setText(_translate("mobilitat_programa", "SUBM"))
        item = self.table_estat_parcs.horizontalHeaderItem(3)
        item.setText(_translate("mobilitat_programa", "BOM"))
        item = self.table_estat_parcs.horizontalHeaderItem(4)
        item.setText(_translate("mobilitat_programa", "NOUS"))
        item = self.table_estat_parcs.horizontalHeaderItem(5)
        item.setText(_translate("mobilitat_programa", "EMIG"))
        self.mni_archivo.setTitle(_translate("mobilitat_programa", "Archivo"))
        self.mni_peticions.setText(_translate("mobilitat_programa", "Carrega peticions"))
        self.mni_vacants.setText(_translate("mobilitat_programa", "Carrega vacants/exces"))
        self.mni_sortir.setText(_translate("mobilitat_programa", "Sortir"))
        self.mni_personal.setText(_translate("mobilitat_programa", "Carrega personal"))
